export const EMPLOYEE_ACTION_TYPE = {
  GET_ALL_EMPLOYEE: "GET_ALL_EMPLOYEE",
  GET_EMPLOYEE_SUCCESS: "GET_EMPLOYEE_SUCCESS",
  GET_EMPLOYEE_FAIL: "GET_EMPLOYEE_FAIL",
  EDITOR_EMPLOYEE: "EDITOR_EMPLOYEE",
  ADD_EMPLOYEE_SUCCESS: "ADD_EMPLOYEE_SUCCESS",
  ADD_EMPLOYEE_FAIL: "ADD_EMPLOYEE_FAIL",
  DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  DELETE_EMPLOYEE_SUCCESS: "DELETE_EMPLOYEE_SUCCESS",
  DELETE_EMPLOYEE_FAIL: "DELETE_EMPLOYEE_FAIL",
  UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
  UPDATE_EMPLOYEE_SUCCESS: "UPDATE_EMPLOYEE_SUCCESS",
  UPDATE_EMPLOYEE_FAIL: "UPDATE_EMPLOYEE_FAIL",
};
